### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by datznoah** [WaduOfficial/Spotify-Inviter#1]
Not sure why this might be, but I encounter this error when starting the bot:
```
  File "bot.py", line 173
    async def on_ready():
        ^
```

Any help is appreciated! :)

**Comment by datznoah** [comment]
```
async def on_ready():
        await client.change_presence(game=discord.Game(name=data['BotStatus']))
        print('bot is ready \nCredits to Wadu')
```

Seems to be where the error is. (in `bot.py`)

**Comment by datznoah** [comment]
` async def redeem(ctx, arg1, arg2, arg3):` is also throwing errors.

**Comment by daggo7532** [comment]
@noahmarshall12 did you end up figuring it out ?

**Comment by daggo7532** [comment]
I got the same errors

**Comment by Neeska** [comment]
HI
you can fix ur problem with this 
https://github.com/Rapptz/discord.py/issues/1125#issuecomment-373958519

**Comment by datznoah** [comment]
Thanks for the help! I'll open a pull request with the correct changes. 👍
