### ISSUE TITLE
lots of Errors, upon issuing the stock command.

### ISSUE THREAD

**Issue by Jelmer8** [WaduOfficial/Spotify-Inviter#4]
My OS is raspbian, and python version 3.6.8. I keep getting lots of errors at issuing the command stock. the redeem command does not create any output in the console, and neither does help. I dont know why i keep getting these errors and the program im coding in wont show me why im getting the error. thanks for any help.
[error.txt](https://github.com/WaduOfficial/Spotify-Inviter/files/3271981/error.txt)

**Comment by Jelmer8** [comment]
found another bot, no solution needed srry for posting.

**Comment by datznoah** [comment]
@Jelmer8 What's the other bot if you don't mind me asking?
